const Menu = [
  {
    id: 1,
    image: "images/image.jpg",
    name: "Halwa Puri",
    category: "Breakfast",
    price: 25 + "rupees",
    description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.`,
  },
  {
    id: 2,
    image: "images/image1.jpg",
    name: "Bread",
    category: "Breakfast",
    price: 25 + "rupees",
    description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.`,
  },
  {
    id: 3,
    image: "images/image2.jpg",
    name: "Biryani",
    category: "Lunch",
    price: 25 + "rupees",
    description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.`,
  },
  {
    id: 4,
    image: "images/image3.jpg",
    name: "Karhai",
    category: "Dinner",
    price: 25 + "rupees",
    description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.`,
  },
  {
    id: 1,
    image: "images/image.jpg",
    name: "Halwa Puri",
    category: "Breakfast",
    price: 25 + "rupees",
    description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.`,
  },
  {
    id: 2,
    image: "images/image1.jpg",
    name: "Bread",
    category: "Breakfast",
    price: 25 + "rupees",
    description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.`,
  },
  {
    id: 3,
    image: "images/image2.jpg",
    name: "Biryani",
    category: "Lunch",
    price: 25 + "rupees",
    description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.`,
  },
  {
    id: 4,
    image: "images/image3.jpg",
    name: "Karhai",
    category: "Dinner",
    price: 25 + "rupees",
    description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.`,
  },
  {
    id: 1,
    image: "images/image.jpg",
    name: "Halwa Puri",
    category: "Breakfast",
    price: 25 + "rupees",
    description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.`,
  },
  {
    id: 2,
    image: "images/image1.jpg",
    name: "Bread",
    category: "Breakfast",
    price: 25 + "rupees",
    description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.`,
  },
  {
    id: 3,
    image: "images/image2.jpg",
    name: "Biryani",
    category: "Lunch",
    price: 25 + "rupees",
    description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.`,
  },
  {
    id: 4,
    image: "images/image3.jpg",
    name: "Karhai",
    category: "Dinner",
    price: 25 + "rupees",
    description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.`,
  },
];
export default Menu;
